services:
  db:
    container_name: promedevusdb-dev
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      timeout: 5s
      interval: 10s
      retries: 10
    networks:
      - app_network

  app:
    container_name: promedevusapp-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    env_file: .env
    environment:
      MQTT_HOST: mqtt
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started
    networks:
      - app_network

  mqtt:
    container_name: promedevusmqtt-dev
    image: eclipse-mosquitto
    restart: always
    mem_limit: 256m
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/passwd:/mosquitto/config/passwd
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/certs:/mosquitto/certs
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
