services:
  db:
    container_name: promedevusdb-dev
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      timeout: 5s
      interval: 10s
      retries: 10
    networks:
      - app_network

  app:
    container_name: promedevusapp-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    env_file: .env
    environment:
      MQTT_HOST: mqtt
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started
    networks:
      - app_network

  mqtt:
    container_name: promedevusmqtt-dev
    image: emqx/nanomq:latest
    restart: always
    mem_limit: 256m
    ports:
      - "8883:8883"
    volumes:
      - ./nanomq/config/nanomq.conf:/etc/nanomq/nanomq.conf
      - ./nanomq/certs:/etc/nanomq/certs:ro
      - ./nanomq/log:/var/log/nanomq
    command: ["nanomq", "start", "--conf", "/etc/nanomq/nanomq.conf"]
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
